server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "${LAVALINK_PASSWORD}"
    sources:
      youtube: false

lavalink.plugins:
  - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.2"
    repository: "https://maven.lavalink.dev/releases"

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true

    clients:
      - ANDROID_VR
      - ANDROID_MUSIC
      - IOS
      - MWEB
      - WEB
      - WEBEMBEDDED
      - TV

    oauth:
      enabled: true
      refreshToken: "${YOUTUBE_OAUTH_REFRESH_TOKEN}"

metrics:
  prometheus:
    enabled: false

sentry:
  dsn: ""

logging:
  level:
    root: INFO
    lavalink: DEBUG
    dev.lavalink.youtube: DEBUG
    com.sedmelluq.discord.lavaplayer.tools.ExceptionTools: DEBUG
    moe.kyokobot.koe.internal.gateway: TRACE
    moe.kyokobot.koe.internal.dave: TRACE

  request:
    enabled: true
    includeHeaders: false
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000
